# Generated by Django 4.2 on 2023-09-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0002_autor_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="editora",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="livraria.editora",
            ),
            preserve_default=False,
        ),
    ]
