# Generated by Django 4.2.6 on 2023-11-01 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0004_itenscompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="data",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itenscompra",
            name="preco_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
